// 00_Config.gs
const SHEET_UI = "ARRIVAGES";
const SHEET_DB = "ARRIVAGES_DB";

const UI_ID_CELL = "B1";
const UI_UPDATED_CELL = "A2";
const UI_CREATED_CELL = "B2";
const UI_ENTREPOT_CELL = "E1";
const UI_QUICK_RANGE = "G4:G305"; // zone multi-lignes
const UI_QUICK_COL = 7;
const UI_QUICK_ROW_START = 4;
const UI_QUICK_ROW_END = 305;

const UI_TABLE_RANGE = "A4:F305";
const UI_TABLE_START_ROW = 4;
const UI_TABLE_ROWS = 302;
const UI_TABLE_COLS = 6;

const SUP_RANGE = "H4:K305";
const SUP_START_ROW = 4;

const LABEL_ADD = "新增";

// ===============
// CONFIG STOCK
// ===============
const SHEET_TEMPLATE_STOCK = "TEMPLATE_STOCK";
const SHEET_STOCK = "STOCK";
const UI_LINEID_COL = 12; // L
const UI_LINEID_ROW_START = 4; // L4

// ===============
// CONFIG MICROSTORE
// ===============
const SHEET_MS_IMPORT = "MS_IMPORT";
const SHEET_MS_IMPORT_DISABLED = "MS_IMPORT_DISABLED";
const SHEET_LOG_IMPORT_EXPORT = "LOG_IMPORT_EXPORT";
const SHEET_MS_EXPORT = "MS_EXPORT";

const MS_IMPORT_FOLDER_ID = "1nIFyDmc4Qg2Kf8gzHWbmcGgRDRWa_mM8";
const MS_IMPORT_DISABLED_FOLDER_ID = "18q6Pi6RBNPR5k4hbKZAVHACcndrmJ4zO";
const MS_EXPORT_DRIVE_FOLDER_ID = "1B2P4SwJbwbPEXW5XO_LSNdIMYA-aYMZa";
const MS_EXPORT_FILENAME = "MS_EXPORT.xlsx";
